# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\Work\PyCharmProjects\ControlLaser_WinSer\\form0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(427, 207)
        Dialog.setMinimumSize(QtCore.QSize(427, 207))
        Dialog.setMaximumSize(QtCore.QSize(427, 207))
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(30, 10, 341, 56))
        self.label_39.setMinimumSize(QtCore.QSize(341, 56))
        self.label_39.setMaximumSize(QtCore.QSize(341, 56))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(70, 80, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border-radius: 16;")
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 140, 121, 41))
        self.pushButton.setMinimumSize(QtCore.QSize(121, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"border-radius: 16;\n"
"background-color: rgb(0, 85, 255,140);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"    background-color: rgb(0, 85, 255,120);\n"
"}\n"
"\n"
"#pushButton:pressed {\n"
"    background-color: rgb(0, 85, 255,100);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"border-radius: 16;\n"
"background-color: rgb(0, 85, 255,140);\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    background-color: rgb(0, 85, 255,120);\n"
"}\n"
"\n"
"#pushButton_2:pressed {\n"
"    background-color: rgb(0, 85, 255,100);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_39.setText(_translate("Dialog", "Выберите COM - Порт"))
        self.pushButton.setText(_translate("Dialog", "ОК"))
        self.pushButton_2.setText(_translate("Dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
